[theme]
primaryColor = "#236548"
backgroundColor = "#F6F8F5"
secondaryBackgroundColor = "#EBF0E9"
textColor = "#203A30"
font = "sans serif"

[server]
maxUploadSize = 20

[browser]
gatherUsageStats = false
